// texts.js
export const texts = [
    { text: "The cat is small and brown. It sleeps all day and plays at night. It chases mice and eats fish. The sun shines brightly, warming the earth. Flowers bloom in many colors. Birds sing songs in the trees. Children laugh and play in the park. The world is big and full of wonders.", voice: "Google UK English Female" },
    { text: "My dog is friendly and playful. She enjoys running in the park and fetching balls. Sometimes, she barks loudly at strangers. The weather is warm and sunny, perfect for outdoor activities. Trees sway gently in the breeze, casting shadows on the ground. People smile as they stroll along the paths.", voice: "Google UK English Male"},
    { text: "The feline creature, adorned with sleek fur, prowls stealthily through the undergrowth. Its keen senses detect the slightest movement, and it pounces with lightning speed. Birds scatter in alarm, their melodious songs abruptly silenced. The dense foliage provides ample cover for the elusive predator. Nature's symphony continues uninterrupted.", voice: "Google UK English Male"},
    { text: "The canine companion, distinguished by its resplendent coat, exudes an aura of nobility. Its demeanor is regal, yet it retains a playful spirit. It frolics with boundless energy, reveling in the thrill of the chase. Its barks resonate with authority, commanding attention from all who cross its path. A loyal guardian, it remains vigilant in safeguarding its territory.", voice: "Google UK English Male"},
    { text: "The equine specimen, characterized by its majestic stature, gallops across the verdant meadow with effortless grace. Its muscles ripple beneath its glossy coat, a testament to its strength and agility. With each powerful stride, it covers vast distances, propelled by an innate sense of freedom. Its mane billows in the wind, a striking contrast against the azure sky. Nature bows in reverence to its magnificence.", voice: "Google UK English Male"},
    { text: "The avian species, distinguished by its iridescent plumage, soars gracefully through the cerulean expanse. Its wings, a marvel of aerodynamic design, propel it with unparalleled precision. It executes intricate aerial maneuvers with effortless fluidity, captivating onlookers with its aerial ballet. Its melodic calls reverberate across the landscape, a symphony of nature's grandeur. Behold the peak of evolutionary perfection.", voice: "Google UK English Male"},
    // Add more paragraphs as needed
];
